openapi: '3.0.0'
info:
  version: 1.0.0
  title: Snacko API
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /clients:
    get:
      summary: List all clients
      operationId: listClients
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of clients
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Clients'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create client
      operationId: createClient
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /clients/{clientId}:
    get:
      summary: Get client info
      operationId: showClientById
      parameters:
        - name: clientId
          in: path
          required: true
          description: The id of the client to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Clients'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /dietplans:
    get:
      summary: List diet plans
      operationId: listDietPlans
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A paged array of diet plans
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DietPlans'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create diet plan
      operationId: createDietPlan
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /dietplans/{planId}:
    get:
      summary: Get diet plan
      operationId: showDietPlanById
      parameters:
        - name: planId
          in: path
          required: true
          description: The id of the diet plan to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DietPlans'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Client:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        goal:
          type: string
    Clients:
      type: array
      items:
        $ref: '#/components/schemas/Client'
    DietPlan:
      required:
        - id
        - title
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
    DietPlans:
      type: array
      items:
        $ref: '#/components/schemas/DietPlan'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string